"""Stellt sicher, dass die Kern-Module nie PySide6/Qt importieren. Nur die Tray-Teile unter
`tapesmith.gui` (tray, hotkey, theme, qtutil, icons) dürfen das."""

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

CORE_MODULES = [
    "tapesmith.cli",
    "tapesmith.pipeline",
    "tapesmith.connection",
    "tapesmith.history",
    "tapesmith.render.compose",
    "tapesmith.templates.store",
    "tapesmith.gui",
    "tapesmith.document.model",
    "tapesmith.document.render",
    "tapesmith.document.from_spec",
    "tapesmith.document.editing",
    "tapesmith.document.snap",
    "tapesmith.document.undo",
    "tapesmith.document.targets",
    "tapesmith.document.generators",
    "tapesmith.templates.render",
    "tapesmith.templates.lint",
    "tapesmith.templates.gallery",
    "tapesmith.templates.series",
    "tapesmith.dataimport.batch",
    "tapesmith.tape.profiles",
    "tapesmith.tape.rolls",
    "tapesmith.tape.preview",
    "tapesmith.render.icons",
    "tapesmith.render.barcode",
    "tapesmith.render.datamatrix",
    "tapesmith.gui.preview_model",
    # Druckdienst, IPC und Kernmodule: der Dienst p12d läuft ohne Qt
    "tapesmith.ipc.protocol",
    "tapesmith.ipc.codec",
    "tapesmith.ipc.pipe",
    "tapesmith.ipc.client",
    "tapesmith.ipc.backend",
    "tapesmith.ipc.launcher",
    "tapesmith.daemon.queue",
    "tapesmith.daemon.probe",
    "tapesmith.daemon.service",
    "tapesmith.daemon.server",
    "tapesmith.daemon.runner",
    "tapesmith.daemon.instance",
    "tapesmith.statusview",
    "tapesmith.clipboard",
    "tapesmith.drives",
    "tapesmith.sshscan",
    "tapesmith.archive",
    "tapesmith.stats",
    "tapesmith.inventory",
    "tapesmith.integration",
    "tapesmith.launch",
    "tapesmith.configcode",
    "tapesmith.backup",
    "tapesmith.numbering",
    "tapesmith.transport.ble",
    "tapesmith.transport.usb",
    "tapesmith.protocol.rawcmd",
    "tapesmith.density",
    "tapesmith.commandreg",
    # HTTP-API im Dienst, Web-Oberfläche, App-Fenster und Selbsttest laufen ohne Qt
    "tapesmith.gui.services",
    "tapesmith.hotkeyspec",
    "tapesmith.webapi.settings_schema",
    "tapesmith.gui.recent",
    "tapesmith.webapi.app",
    "tapesmith.webapi.server",
    "tapesmith.webapi.labels",
    "tapesmith.webapi.routes_templates",
    "tapesmith.webapi.routes_editor",
    "tapesmith.webapi.routes_data",
    "tapesmith.webapi.routes_settings",
    "tapesmith.webapi.routes_system",
    "tapesmith.webapi.actions",
    "tapesmith.webapi.settings_schema",
    "tapesmith.webui",
    "tapesmith.webui.browser",
    "tapesmith.selftest",
    "tapesmith.cli_cmds.app",
    "tapesmith.cli_cmds.gui",
    # Homelab-Integrationen, ihre Routen und CLI-Befehle laufen ohne Qt
    "tapesmith.integrations",
    "tapesmith.integrations.assetnote",
    "tapesmith.integrations.assets",
    "tapesmith.integrations.cliprint",
    "tapesmith.integrations.codescan",
    "tapesmith.integrations.credentials",
    "tapesmith.integrations.errors",
    "tapesmith.integrations.frontmatter",
    "tapesmith.integrations.homeassistant",
    "tapesmith.integrations.httpclient",
    "tapesmith.integrations.kleinanzeigen",
    "tapesmith.integrations.mcpclient",
    "tapesmith.integrations.netbox",
    "tapesmith.integrations.obsidian",
    "tapesmith.integrations.paperless",
    "tapesmith.integrations.plausi",
    "tapesmith.integrations.proxmox",
    "tapesmith.integrations.scancache",
    "tapesmith.integrations.settings",
    "tapesmith.integrations.shortlink",
    "tapesmith.integrations.snippet",
    "tapesmith.integrations.tia606",
    "tapesmith.integrations.winclip",
    "tapesmith.integrations.zfsreplace",
    "tapesmith.webapi.homelab_common",
    "tapesmith.webapi.homelab_routers",
    "tapesmith.webapi.routes_assets",
    "tapesmith.webapi.routes_codescan",
    "tapesmith.webapi.routes_ha",
    "tapesmith.webapi.routes_homelab",
    "tapesmith.webapi.routes_kabel",
    "tapesmith.webapi.routes_kleinanzeigen",
    "tapesmith.webapi.routes_paperless",
    "tapesmith.webapi.routes_plausi",
    "tapesmith.webapi.routes_proxmox",
    "tapesmith.webapi.routes_vault",
    "tapesmith.webapi.routes_zfs",
    "tapesmith.cli_cmds.asn",
    "tapesmith.cli_cmds.asset",
    "tapesmith.cli_cmds.asset_notiz",
    "tapesmith.cli_cmds.batterie",
    "tapesmith.cli_cmds.garantie",
    "tapesmith.cli_cmds.homelab",
    "tapesmith.cli_cmds.ka",
    "tapesmith.cli_cmds.kabel",
    "tapesmith.cli_cmds.kurz",
    "tapesmith.cli_cmds.platte",
    "tapesmith.cli_cmds.plausi",
    "tapesmith.cli_cmds.proxmox",
    "tapesmith.cli_cmds.sn_scan",
    "tapesmith.cli_cmds.vault",
    # LAN-Zugriff, Tokens, Automatisierung (Hotfolder, MQTT, Telegram) und MCP im Dienst
    "tapesmith.automation",
    "tapesmith.automation.facade",
    "tapesmith.automation.hotfolder",
    "tapesmith.automation.mqtt",
    "tapesmith.automation.telegram",
    "tapesmith.mcpserver",
    "tapesmith.mcpserver.backends",
    "tapesmith.mcpserver.server",
    "tapesmith.mcpserver.tools",
    "tapesmith.apitokens",
    "tapesmith.secretref",
    "tapesmith.netinfo",
    "tapesmith.sourcelimits",
    "tapesmith.daemon.addons",
    "tapesmith.webapi.access",
    "tapesmith.webapi.security",
    "tapesmith.webapi.ratelimit",
    "tapesmith.webapi.routes_access",
    "tapesmith.webapi.routes_short",
    "tapesmith.webapi.routes_family",
    "tapesmith.webapi.mcp_http",
    "tapesmith.cli_cmds.token",
    "tapesmith.cli_cmds.secret",
    "tapesmith.cli_cmds.mcp",
    "tapesmith.cli_cmds.hotfolder",
    "tapesmith.cli_cmds.mqtt",
    "tapesmith.cli_cmds.telegram",
    # Sprache, Problem melden, Installer, Update, Entwürfe und App-Fenster laufen ohne Qt
    "tapesmith.i18n",
    "tapesmith.support",
    "tapesmith.install",
    "tapesmith.install.layout",
    "tapesmith.install.junction",
    "tapesmith.install.processes",
    "tapesmith.install.shortcuts",
    "tapesmith.install.registry",
    "tapesmith.install.installer",
    "tapesmith.install.venv",
    "tapesmith.install.legacy",
    "tapesmith.install.uninstaller",
    "tapesmith.update",
    "tapesmith.update.apply",
    "tapesmith.update.errors",
    "tapesmith.update.manifest",
    "tapesmith.update.service",
    "tapesmith.update.signing",
    "tapesmith.update.sources",
    "tapesmith.update.state",
    "tapesmith.automation.update",
    "tapesmith.webapi.drafts",
    "tapesmith.webapi.routes_drafts",
    "tapesmith.webapi.routes_support",
    "tapesmith.webapi.routes_update",
    "tapesmith.cli_cmds.report",
    "tapesmith.cli_cmds.install",
    "tapesmith.cli_cmds.uninstall",
    "tapesmith.__main__",
    "tapesmith.cli_cmds.update",
]


def test_kern_module_importieren_kein_qt():
    imports = "\n".join(f"import {name}" for name in CORE_MODULES)
    code = f"{imports}\nimport sys\nprint('PySide6' in sys.modules)\n"

    env = dict(os.environ)
    src_path = str(REPO_ROOT / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = src_path if not existing else os.pathsep.join([src_path, existing])
    env.setdefault("QT_QPA_PLATFORM", "offscreen")

    result = subprocess.run(
        [sys.executable, "-c", code],
        env=env,
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=True,
    )

    assert result.stdout.strip() == "False", result.stdout + result.stderr
